### ISSUE TITLE
Unable to create database using sqlachemy

### ISSUE THREAD

**Issue by harksodje** [lmeunier/flask-compressor#4]

**Comment by harksodje** [comment]
`from flask import Flask, render_template, make_response, request
from flask_sqlalchemy import SQLAlchemy
from os import path
basedir = path.abspath(path.dirname(__file__))
# or basedir = ### **os.path.abspath(os.path.dirname(__file__))**

app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] ='sqlite:///' + path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True
app.config['SQLALCHEMY_TRACK_MODIFICATIONS']= False
db = SQLAlchemy(app)

class User(db.Model):
    __tablename__ = 'flasksqlalchemy-tutorial-users'
    id = db.Column(db.Integer, primary_key = True, nullable = False, unique = True)
    username = db.Column(db.String(64), index = False, unique = True, nullable = False)
    email = db.Column(db.String(60), index = True, unique = True, nullable = False)
    created = db.Column(db.DateTime, index = False, unique = False, nullable = False)
    bio = db.Column(db.Text, index = False, unique = False, nullable = False )
    admin = db.Column(db.Boolean, index = False, unique = False, nullable = False)
    def __repr(self):
        return 'User {}>'.format(self.username)

@app.route('/', methods= ['GET'])
def user_records():
    username = request.args.get('user')
    email = request.args.get('email')
    
    if username and email:
        existing_user = User.query.filter(
            User.username == username or User.email == email).first()
        if existing_user:
            return make_response(f'{username} {email} already created')
        new_user = User(
            username = username, 
            email = email, 
            created = dt.now(),
            bio = "In west Philadelphia born and raised,\
                on the playground is where I spent most of my days",
            admin = False
        )
        db.session.add(new_user) #add new user
        db.session.commit() # commit all changes
        redirect(url_for('user_records'))
        return render_template('users.jinja2', users = User.query.all(), title = "Show Users")
@app.route('/', methods = ['GET'])
def create_user():
    return render_template('users.jinja2', users = User.query.all(), title = "Show Users")

**Comment by harksodje** [comment]
ktop\Learning\project>database.py

(env) C:\Users\user\Desktop\Learning\project>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

Type "help", "copyright", "credits" or "license" for more information.
>>> from database import db
>>> db.create_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 561, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 966, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "c:\users\user\anaconda3\lib\site-packages\sqlalchemy\engine\__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "c:\users\user\anaconda3\lib\site-packages\sqlalchemy\engine\strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "c:\users\user\anaconda3\lib\site-packages\sqlalchemy\dialects\sqlite\pysqlite.py", line 426, in dbapi
    from sqlite3 import dbapi2 as sqlite
  File "c:\users\user\anaconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "c:\users\user\anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified module could not be found.
>>> cmd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'cmd' is not defined
>>> from database.py import db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'database.py'; 'database' is not a package
>>> from database import db
>>> db.create_all()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 956, in get_engine
    return connector.get_engine()
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 561, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "c:\users\user\anaconda3\lib\site-packages\flask_sqlalchemy\__init__.py", line 966, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "c:\users\user\anaconda3\lib\site-packages\sqlalchemy\engine\__init__.py", line 479, in create_engine
    return strategy.create(*args, **kwargs)
  File "c:\users\user\anaconda3\lib\site-packages\sqlalchemy\engine\strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "c:\users\user\anaconda3\lib\site-packages\sqlalchemy\dialects\sqlite\pysqlite.py", line 426, in dbapi
    from sqlite3 import dbapi2 as sqlite
  File "c:\users\user\anaconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "c:\users\user\anaconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified module could not be found.
>>>
